Refactor/gerenciar notificacoes
AgroMart/api pull request #42
Opened 2023-03-17 11:33 UTC by Fealps

## Tipo da mudança
- [ ] Adaptativa
- [ ] Corretiva
- [ ] Emergencial
- [x] Perfectiva

## Descrição das mudanças

Mantém o funcionamento do gerenciamento de notificações de uma CSA no AgroMart. Isso incluí criar, editar e excluir notificações.

Closes #41

2023-03-17 12:05 UTC, giovannabbottino commented
Esse PR está incorreto, refaça.

2023-03-17 12:07 UTC, giovannabbottino requested changes
Está indo para a branch errada, o nome está incorreto e não deve colocar milestone

2023-03-17 12:13 UTC, giovannabbottino reviewed
Não precisa baixar nenhum módulo para a funcionar com o firebase? É só isso que precisa para integrar com o firebase?

2023-03-17 12:13 UTC, giovannabbottino commented on src/api/notificacao/content-types/notificacao/schema.json
> +    "pluralName": "notificacaos",
```suggestion
    "pluralName": "notificacoes",
```

2023-04-02 12:39 UTC, giovannabbottino commented
Precisa: 
- [ ] retirar o `api` do path 
- [ ] refazer codigo para que conecte no banco
- [ ] refazer teste para que delete o banco no final

2023-04-02 15:48 UTC, giovannabbottino commented
Não é possivel retirar o prefix `api` na versao 4 

Fonte: https://forum.strapi.io/t/customize-api-prefix-for-apis/13648/8

2023-04-02 20:14 UTC, giovannabbottino commented
Não é possivel retirar o `api` do path. https://forum.strapi.io/t/customize-api-prefix-for-apis/13648/7

2023-04-10 22:11 UTC, giovannabbottino commented
@Fealps terminei aqui se puder revisar

2023-04-10 22:51 UTC, giovannabbottino commented
Acabei de perceber que o notificações não foi deletado, tem que deletar antes de fazer o merge

2023-04-10 22:58 UTC, Fealps reviewed
ok

2023-04-10 22:59 UTC, merged